### ISSUE TITLE
Option to exclude imports from beeing resolved

### ISSUE THREAD

**Issue by pfeigl** [SimplrJS/scss-bundle#42]
There doesn't seem to be an option to exclude any imports from beeing resolved.
We are building a library which depends on angular material and we provide our own theme.

Therefore we have an import like this in our styles.scss which is later re-used:
```scss
@import '~@angular/material/theming';
```

Now what we want to accomplish is, that all "our" styles are actually bundled into one big scss file, but external style files are just beeing kept as imports so that they can be imported later on in the actual application (which also has a reference to angular material and therefor can resolve it).

**Comment by DovydasNavickas** [comment]
Hmmm... So you want to define a list of imports, which in this case would be only this one:

```scss
@import '~@angular/material/theming';
```

And all imports in that list should not be bundled, but should still be kept in the output, right?

E.g.
file1.scss
```scss
@import '~@angular/material/theming';
@import './file2';

.red {
    background: red;
}
```

file2.scss
```scss
.blue {
    background: blue;
}
```

And resulting file when bundling `file1.scss` would be:
```scss
@import '~@angular/material/theming';
.blue {
    background: blue;
}

.red {
    background: red;
}
```

Is I understand correctly what you want? 🙂
